In [7]:
import numpy as np

In [34]:
import scipy.spatial

In [1]:
import cwipc

In [3]:
pc = cwipc.cwipc_read("genregtest03/genregtest03.ply", 0)

[pcl::PLYReader] genregtest03/genregtest03.ply:26: property 'float32 focal' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:27: property 'float32 scalex' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:28: property 'float32 scaley' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:29: property 'float32 centerx' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:30: property 'float32 centery' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:33: property 'float32 k1' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:34: property 'float32 k2' of element 'camera' is not handled


In [3]:
# pc = cwipc.cwipc_read("genregtest003/genregtest003.ply", 0)

[pcl::PLYReader] genregtest03/genregtest03.ply:26: property 'float32 focal' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:27: property 'float32 scalex' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:28: property 'float32 scaley' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:29: property 'float32 centerx' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:30: property 'float32 centery' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:33: property 'float32 k1' of element 'camera' is not handled
[pcl::PLYReader] genregtest03/genregtest03.ply:34: property 'float32 k2' of element 'camera' is not handled


In [10]:
pc_cam1 = cwipc.cwipc_tilefilter(pc, 1)
np_cam1 = np.ctypeslib.as_array(pc_cam1.get_points())

In [14]:
pc_cam2 = cwipc.cwipc_tilefilter(pc, 2)
np_cam2 = np.ctypeslib.as_array(pc_cam2.get_points())

In [30]:
xyz_cam1 = np_cam1[['x','y','z']]

In [31]:
xyz_cam2 = np_cam2[['x','y','z']]

In [47]:
points_cam1 = np.column_stack([xyz_cam1['x'],xyz_cam1['y'],xyz_cam1['z']])

In [50]:
points_cam2 = np.column_stack([xyz_cam2['x'],xyz_cam2['y'],xyz_cam2['z']])

In [49]:
tree_cam1 = scipy.spatial.KDTree(points_cam1)

In [51]:
tree_cam2 = scipy.spatial.KDTree(points_cam2)

In [52]:
dists_1to2, indices_1to2 = tree_cam2.query(points_cam1)

In [61]:
dists_2to1, indices_2to1 = tree_cam1.query(points_cam2)

In [62]:
min(dists_1to2), min(dists_2to1)

(0.011494501320109388, 0.011494501320109388)

In [64]:
max(dists_1to2), max(dists_2to1)

(0.44958586087031543, 0.41304563137057015)

In [67]:
histogram_1to2, edges_1to2 = np.histogram(dists_1to2, bins=100)

In [68]:
histogram_2to1, edges_2to1 = np.histogram(dists_2to1, bins=100)

In [69]:
histogram_1to2, edges_1to2

(array([3545, 5043, 5956, 4850,  516,  553,  558,  513,  482,  482,  489,
         496,  493,  507,  504,  500,  505,  517,  528,  520,  528,  529,
         536,  535,  550,  553,  543,  504,  603,  576,  555,  548,  566,
         549,  550,  560,  555,  557,  551,  556,  550,  552,  539,  552,
         545,  526,  529,  535,  527,  494,  514,  508,  506,  510,  510,
         481,  492,  477,  486,  463,  474,  489,  461,  469,  447,  439,
         423,  500,  425,  423,  431,  421,  441,  415,  421,  388,  410,
         424,  391,  362,  416,  387,  357,  378,  385,  353,  344,  377,
         330,  332,  361,  294,  330,  275,  266,  266,  195,  214,  140,
         161]),
 array([0.0114945 , 0.01587541, 0.02025633, 0.02463724, 0.02901816,
        0.03339907, 0.03777998, 0.0421609 , 0.04654181, 0.05092272,
        0.05530364, 0.05968455, 0.06406546, 0.06844638, 0.07282729,
        0.07720821, 0.08158912, 0.08597003, 0.09035095, 0.09473186,
        0.09911277, 0.10349369, 0.1078746 , 0.

In [70]:
histogram_1to2,edges_1to2

(array([3545, 5043, 5956, 4850,  516,  553,  558,  513,  482,  482,  489,
         496,  493,  507,  504,  500,  505,  517,  528,  520,  528,  529,
         536,  535,  550,  553,  543,  504,  603,  576,  555,  548,  566,
         549,  550,  560,  555,  557,  551,  556,  550,  552,  539,  552,
         545,  526,  529,  535,  527,  494,  514,  508,  506,  510,  510,
         481,  492,  477,  486,  463,  474,  489,  461,  469,  447,  439,
         423,  500,  425,  423,  431,  421,  441,  415,  421,  388,  410,
         424,  391,  362,  416,  387,  357,  378,  385,  353,  344,  377,
         330,  332,  361,  294,  330,  275,  266,  266,  195,  214,  140,
         161]),
 array([0.0114945 , 0.01587541, 0.02025633, 0.02463724, 0.02901816,
        0.03339907, 0.03777998, 0.0421609 , 0.04654181, 0.05092272,
        0.05530364, 0.05968455, 0.06406546, 0.06844638, 0.07282729,
        0.07720821, 0.08158912, 0.08597003, 0.09035095, 0.09473186,
        0.09911277, 0.10349369, 0.1078746 , 0.